### ISSUE TITLE
static members

### ISSUE THREAD

**Issue by TobiasPSP** [SeeminglyScience/ImpliedReflection#5]
Am I missing something, or is there no support yet for static members such as [Math]:: <--- ?
Other than that, I am deeply impressed by this awesome work!

**Comment by SeeminglyScience** [comment]
There is support, it's just not *as* automatic.  The delegate that PowerShell uses internally for member binding is for instance members only.  However, the custom one I inject will also add static members to the cache when it's either getting members for an instance, or getting members of a `Type` object.

In other words, there's two easy ways to force static member binding:

**Note:** Non-public constructors will be added as `_ctor` due to some issues in the `PSCreateInstanceBinder`.

## Send `[Math]` to output interactively.

Needs to be interactive, there's a hook into `Out-Default`.  This is typically how I do it.

```powershell
PS> [Math]::<tab>
E                Atan             Cosh             IEEERemainder    Pow              Sinh
PI               Atan2            DivRem           Log              ReferenceEquals  Sqrt
Abs              BigMul           Equals           Log10            Round            Tan
Acos             Ceiling          Exp              Max              Sign             Tanh
Asin             Cos              Floor            Min              Sin              Truncate

PS> [Math]
Public Sealed Abstract Generic Name                           BaseType             Members
------ ------ -------- ------- ----                           --------             -------
 True   True    True    False  Math                           Object                    83

PS> [Math]::<tab>
doubleRoundLimit     Asin                 Equals               Max                  SplitFractionDouble
E                    Atan                 Exp                  Min                  Sqrt
maxRoundingDigits    Atan2                Floor                Pow                  Tan
PI                   BigMul               IEEERemainder        ReferenceEquals      Tanh
roundPower10Double   Ceiling              InternalRound        Round                Truncate
Abs                  Cos                  InternalTruncate     Sign
AbsHelper            Cosh                 Log                  Sin
Acos                 DivRem               Log10                Sinh
```

## Trigger member binding on the `Type` object

This one can be done non-interactively, but is a little bit more obtuse.

```powershell
# Forces PowerShell to get members as PSMemberInfo objects via the delegate.
# This is also more or less the only thing added to Out-Default
$null = [Math].psobject.Members[0]
[Math]::maxRoundingDigits
# 15
```

I considered adding a proxy `TabExpansion2` that looks for `TypeExpressionAst`'s and triggers member binding.  Ultimately I decided that would be a little be more confusing, because if you didn't use tab completion, nothing would bind.  Ideally I'd be able to find a way to completely hook into static binding like I did instance, but it looks like it's all direct calls to the `DotNetAdapter` since there isn't any non-CLR static members.

> Other than that, I am deeply impressed by this awesome work!

Thank you! 😄

**Comment by TobiasPSP** [comment]
Many thx! Awesome stuff.

As you may know we are organizing the psconf.eu annual community conference in Hannover Germany, next will be in June 4-7. I could see you delivering awesome sessions. Would you be interested?

Where are you located?

Cheerio
Tobias

**Comment by SeeminglyScience** [comment]
> I could see you delivering awesome sessions. Would you be interested?

Thank you for the kind words! 😄 I'd love to but I'm in the US unfortunately.

**Comment by TobiasPSP** [comment]
Hi Patrick,

 

your name sounded a bit German so I was intrigued to believe you might be from the area 😊!

That said, we do have speakers and delegates from the US that come and visit psconf.eu. So just in case you were interested, or would want to combine a Europe trip with the conference, here are all the details for speakers: https://www.papercall.io/psconfeu2019

 

Anyhow, your extension is amazing. Initially, I assumed you added the nonpublic members via attached members (Add-Member) only to find out that they are not. Could you explain in a sentence or two how these properties are attached? Here is why: when you explore nonpublic members with your extension, in order to permanently use these members, the code would have to be changed (or else your module would always be required). If the nonpublic members would be exposed via Add-Member, it would be easy for PowerShell users to look up the code and (possibly automatically) convert the PS code into code that runs without your module. Since the code is not exposed via attached members, PS users would need to figure out themselves how to invoke these members which is no rocket science but still an effort.

 

In a nutshell, it would be awesome to think about a feature that auto-converts ad-hoc code that uses your extension into stand-alone code that uses reflection to access the members. This way, your extension could serve as a super-convenient way to explore things, and once a script is ready to distribute, it could be converted into a self-contained script.

 

Best regards,

Tobias

 

Von: Patrick Meinecke [mailto:notifications@github.com] 
Gesendet: Donnerstag, 27. September 2018 22:54
An: SeeminglyScience/ImpliedReflection <ImpliedReflection@noreply.github.com>
Cc: Dr. Tobias Weltner <tobias.weltner@scriptinternals.de>; Author <author@noreply.github.com>
Betreff: Re: [SeeminglyScience/ImpliedReflection] static members (#5)

 

There is support, it's just not as automatic. The delegate that PowerShell uses internally for member binding is for instance members only. However, the custom one I inject will also add static members to the cache when it's either getting members for an instance, or getting members of a Type object.

In other words, there's two easy ways to force static member binding:

Note: Non-public constructors will be added as _ctor due to some issues in the PSCreateInstanceBinder.


Send [Math] to output interactively.


Needs to be interactive, there's a hook into Out-Default. This is typically how I do it.

PS> [Math]::<tab>
E                Atan             Cosh             IEEERemainder    Pow              Sinh
PI               Atan2            DivRem           Log              ReferenceEquals  Sqrt
Abs              BigMul           Equals           Log10            Round            Tan
Acos             Ceiling          Exp              Max              Sign             Tanh
Asin             Cos              Floor            Min              Sin              Truncate
 
PS> [Math]
Public Sealed Abstract Generic Name                           BaseType             Members
------ ------ -------- ------- ----                           --------             -------
 True   True    True    False  Math                           Object                    83
 
PS> [Math]::<tab>
doubleRoundLimit     Asin                 Equals               Max                  SplitFractionDouble
E                    Atan                 Exp                  Min                  Sqrt
maxRoundingDigits    Atan2                Floor                Pow                  Tan
PI                   BigMul               IEEERemainder        ReferenceEquals      Tanh
roundPower10Double   Ceiling              InternalRound        Round                Truncate
Abs                  Cos                  InternalTruncate     Sign
AbsHelper            Cosh                 Log                  Sin
Acos                 DivRem               Log10                Sinh

Trigger member binding on the Type object


This one can be done non-interactively, but is a little bit more obtuse.

# Forces PowerShell to get members as PSMemberInfo objects via the delegate.
# This is also more or less the only thing added to Out-Default
$null = [Math].psobject.Members[0]
[Math]::maxRoundingDigits
# 15

I considered adding a proxy TabExpansion2 that looks for TypeExpressionAst's and triggers member binding. Ultimately I decided that would be a little be more confusing, because if you didn't use tab completion, nothing would bind. Ideally I'd be able to find a way to completely hook into static binding like I did instance, but it looks like it's all direct calls to the DotNetAdapter since there isn't any non-CLR static members.

Other than that, I am deeply impressed by this awesome work!

Thank you! 😄

**Comment by SeeminglyScience** [comment]
> Could you explain in a sentence or two how these properties are attached?

So when PowerShell goes to get instance members for an object, it calls a few statically stored delegates.  These delegates are stored in a object called a `CollectionEntry`, and they are kept in `PSObject.memberCollection`, `PSObject.methodCollection`, and `PSObject.propertyCollection`.  There is a `CollectionEntry` for adapted members, typetable members, and CLR members.  I replace the `GetMember` and `GetMembers` delegates for the CLR collection entry, effectively taking full control of member binding.

I didn't used to do this, this module actually used to be written entirely in PowerShell.  When that was the case all I could do was proxy `Out-Default` and add the members manually.  This is was pretty close to what you describe, but [it's a lot more involved](https://github.com/SeeminglyScience/ImpliedReflection/blob/051c33671a741f82cae6544c65d270e20fb47459/module/Public/Add-PrivateMember.ps1) than you may think.  In order to bind them as actual `PSMethod` objects instead of something like `PSScriptMethod` you need to use a lot non-public constructors and add the method to the `DotNetAdapter`'s cache. It's also quite fragile.  Any PowerShell update can and *will* break this module.  I can update the module for future versions of PowerShell, but I can't update code generated for the user.  There's already been some discussion on [how to break it](https://twitter.com/lzybkr/status/1039361916030701569) 😉 

Sorry, that's a bit more than a sentence or two 😄 

> Since the code is not exposed via attached members, PS users would need to figure out themselves how to invoke these members which is no rocket science but still an effort.

Honestly... I'm okay with that.  There is inherit risk involved in using non-public API's, a little bit of research helps ensure you know what you're signing up for.  My intention is not to make it really easy to develop with them, but instead to facilitate exploration and debugging.  These days I mainly use this for debugging binary modules or projects like PowerShellEditorServices.

That said, I do have a pretty easy way to generate reflection statements in PSES enabled editors.  I'm working on a overhaul for [`EditorServicesCommandSuite`](https://github.com/SeeminglyScience/EditorServicesCommandSuite/tree/0.5.0) which has this refactor option:

![expandmemberexpression](https://user-images.githubusercontent.com/24977523/46285045-03fc8c80-c548-11e8-81c0-d858c3aadb51.gif)

**Comment by SeeminglyScience** [comment]
Also worth noting, even if you did strip out the old PowerShell code and use that directly, it wasn't able to handle constructors.

[Here's the code](https://github.com/SeeminglyScience/ImpliedReflection/blob/df89f90070d464c918fa49c6497f2fc7575e634a/src/ImpliedReflection/MemberData.cs#L174) that generates the proxy method for constructors.  It's an interesting read imo, but here's a comment from there that sums it up

```raw
Binding non-public constructors ended up being far more complicated than I expected.
Initially I attemped to add bind them the same way we bind all other static methods,
but unfortunately the PSCreateInstanceBinder doesn't _really_ use the cache. Instead
it calls Type.GetConstructors, which will only find public constructors and ignore
the cache completely.

So I had the idea to create a DynamicMethod that would call the constructor and add
that to the cache. Unfortunately the PowerShell binder checks MethodBase.DeclaringType
at a few different points, which ends up throwing a NullReferenceException.

That's when I decided I needed to dynamically create a class to store the static
methods and get past the binder. Easy enough, unfortunately you can't skip visibility
(i.e. Public/Protected/etc) checks with MethodBuilder like you can with DynamicMethod.

Finally, I decided to go with saving the original DynamicMethod to a static field as
a delegate and having the generated method invoke that delegate. I'm not particularly
happy with this, but it works.
```

**Comment by TobiasPSP** [comment]
Hi Patrick,

 

many thanks for your quick and detailed response.

I completely follow you in terms of using your module to facilitate exploration rather than produce production code that depends on fragile private members.

Your module makes exploration so much easier. Thank you very much for investing time and brains into this. Awesome work!

 

 

 

Von: Patrick Meinecke [mailto:notifications@github.com] 
Gesendet: Montag, 1. Oktober 2018 13:59
An: SeeminglyScience/ImpliedReflection <ImpliedReflection@noreply.github.com>
Cc: Dr. Tobias Weltner <tobias.weltner@scriptinternals.de>; Author <author@noreply.github.com>
Betreff: Re: [SeeminglyScience/ImpliedReflection] static members (#5)

 

Also worth noting, even if you did strip out the old PowerShell code an use that directly, it wasn't able to handle constructors.

Here's the code <https://github.com/SeeminglyScience/ImpliedReflection/blob/df89f90070d464c918fa49c6497f2fc7575e634a/src/ImpliedReflection/MemberData.cs#L174>  that generates the proxy method for constructors. It's an interesting read imo, but here's a comment from there that sums it up

Binding non-public constructors ended up being far more complicated than I expected.
Initially I attemped to add bind them the same way we bind all other static methods,
but unfortunately the PSCreateInstanceBinder doesn't _really_ use the cache. Instead
it calls Type.GetConstructors, which will only find public constructors and ignore
the cache completely.
 
So I had the idea to create a DynamicMethod that would call the constructor and add
that to the cache. Unfortunately the PowerShell binder checks MethodBase.DeclaringType
at a few different points, which ends up throwing a NullReferenceException.
 
That's when I decided I needed to dynamically create a class to store the static
methods and get past the binder. Easy enough, unfortunately you can't skip visibility
(i.e. Public/Protected/etc) checks with MethodBuilder like you can with DynamicMethod.
 
Finally, I decided to go with saving the original DynamicMethod to a static field as
a delegate and having the generated method invoke that delegate. I'm not particularly
happy with this, but it works.

**Comment by SeeminglyScience** [comment]
I forgot to close this... almost four years ago apparently? Oops!

Anyway, I've also just released a new version that just always works without needing any of the weird tricks I described above.
